name: Monitor ANTT

on:
  schedule:
    - cron: "0 10 * * *"  # Roda todo dia às 07h Brasília
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python monitor_antt.py

      - name: Fazer upload dos arquivos HTML para depuração
        uses: actions/upload-artifact@v3
        with:
          name: html-outputs
          path: response_antt_selenium_*.html

      - name: Commit se houve atualização
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add ultima_resolucao.txt
            git commit -m "Atualizando última resolução detectada"
            git push
          else
            echo "Nenhuma mudança detectada."
          fi
